document.write(2 == 2);
document.write("<br>");
document.write(3 === 3);
document.write("<br>");
document.write(2 != 1);
document.write("<br>");
document.write(2 !== 3);
document.write("<br>");
document.write(3 > 2);
document.write("<br>");
document.write(2 < 3);
document.write("<br>");
document.write(2 >= 1);
document.write("<br>");
document.write(2 <= 4);
document.write("<br>");
document.write(null == undefined);
document.write("<br>");
document.write(null === undefined);
document.write("<br>");
